
const films = [
{"movieID":305,"movieTitle":"Amen.","movieYear":2012,"movieRating":4},
{"movieID":470,"movieTitle":"I Spy","movieYear":1988,"movieRating":3},
{"movieID":413,"movieTitle":"Silent Night, Bloody Night","movieYear":2001,"movieRating":4},
{"movieID":495,"movieTitle":"Eden","movieYear":1997,"movieRating":1},
{"movieID":213,"movieTitle":"Shiver (Eskalofrío)","movieYear":1966,"movieRating":3},
{"movieID":224,"movieTitle":"Demon Wind","movieYear":2000,"movieRating":3},
{"movieID":493,"movieTitle":"Finding Fela!","movieYear":1995,"movieRating":1},
{"movieID":106,"movieTitle":"Dodsworth","movieYear":1993,"movieRating":3},
{"movieID":222,"movieTitle":"Flash of Genius","movieYear":2005,"movieRating":5},
{"movieID":272,"movieTitle":"Bachelor Apartment","movieYear":2002,"movieRating":5},
{"movieID":476,"movieTitle":"Jive Turkey","movieYear":2010,"movieRating":1},
{"movieID":322,"movieTitle":"Horse Rebellion, The (Pulakapina)","movieYear":1992,"movieRating":5},
{"movieID":256,"movieTitle":"Leave","movieYear":2009,"movieRating":4},
{"movieID":372,"movieTitle":"Bass Ackwards","movieYear":2006,"movieRating":2},
{"movieID":370,"movieTitle":"Anniversary Party, The","movieYear":2010,"movieRating":1},
{"movieID":386,"movieTitle":"Mysterious Mr. Moto","movieYear":1985,"movieRating":2},
{"movieID":205,"movieTitle":"Slipper and the Rose, The","movieYear":2012,"movieRating":1},
{"movieID":391,"movieTitle":"Uncertainty","movieYear":2002,"movieRating":5},
{"movieID":283,"movieTitle":"Down Terrace","movieYear":2008,"movieRating":1},
{"movieID":299,"movieTitle":"Seven-Per-Cent Solution, The","movieYear":2000,"movieRating":1},
{"movieID":418,"movieTitle":"Strawberry Wine","movieYear":2004,"movieRating":1},
{"movieID":465,"movieTitle":"Iris","movieYear":2004,"movieRating":2},
{"movieID":336,"movieTitle":"Jackass Number Two","movieYear":1986,"movieRating":1},
{"movieID":267,"movieTitle":"Tales That Witness Madness","movieYear":1978,"movieRating":3},
{"movieID":116,"movieTitle":"Invisible Sign, An","movieYear":1995,"movieRating":4},
{"movieID":286,"movieTitle":"My Stepmother Is an Alien","movieYear":2008,"movieRating":4},
{"movieID":239,"movieTitle":"I Am Taraneh, I Am Fifteen Years Old (Man, taraneh, panzdah sal daram)","movieYear":2008,"movieRating":1},
{"movieID":460,"movieTitle":"Mummy's Curse, The","movieYear":1998,"movieRating":2},
{"movieID":109,"movieTitle":"Nixon by Nixon: In His Own Words","movieYear":2010,"movieRating":1},
{"movieID":398,"movieTitle":"Bride of Boogedy","movieYear":1964,"movieRating":3},
{"movieID":237,"movieTitle":"Bugs Bunny / Road Runner Movie, The (a.k.a. The Great American Chase)","movieYear":1986,"movieRating":5},
{"movieID":159,"movieTitle":"Manson","movieYear":2001,"movieRating":4},
{"movieID":415,"movieTitle":"My Boy","movieYear":2002,"movieRating":5},
{"movieID":246,"movieTitle":"My Way to Olympia (Mein Weg nach Olympia)","movieYear":2001,"movieRating":3},
{"movieID":114,"movieTitle":"Evenings on a Farm near Dikanka","movieYear":1997,"movieRating":4},
{"movieID":296,"movieTitle":"Honor Among Lovers","movieYear":2006,"movieRating":5},
{"movieID":368,"movieTitle":"Two Tars","movieYear":1996,"movieRating":5},
{"movieID":394,"movieTitle":"Red White & Blue","movieYear":1992,"movieRating":4},
{"movieID":197,"movieTitle":"Five, The (Gonin)","movieYear":2000,"movieRating":3},
{"movieID":210,"movieTitle":"Classic, The (Klassikko)","movieYear":1992,"movieRating":3},
{"movieID":294,"movieTitle":"Night Tide","movieYear":1999,"movieRating":5},
{"movieID":295,"movieTitle":"Heart Like a Wheel","movieYear":1995,"movieRating":5},
{"movieID":171,"movieTitle":"No Flesh Shall Be Spared","movieYear":2007,"movieRating":3},
{"movieID":467,"movieTitle":"Eila","movieYear":2010,"movieRating":3},
{"movieID":115,"movieTitle":"Blast","movieYear":1995,"movieRating":2},
{"movieID":244,"movieTitle":"American Virgin","movieYear":2008,"movieRating":2},
{"movieID":415,"movieTitle":"Last Mountain, The","movieYear":2007,"movieRating":3},
{"movieID":457,"movieTitle":"Psycho","movieYear":2002,"movieRating":2},
{"movieID":300,"movieTitle":"My Joy (Schastye moe)","movieYear":1987,"movieRating":3},
{"movieID":144,"movieTitle":"Prize of Peril, The (Prix du danger, Le)","movieYear":2012,"movieRating":4}
];
